#!/usr/bin/env bash
if [[ -z "$INTERFACE" ]]; then
  INTERFACE="${BLOCK_INSTANCE:-wlan0}"
fi
[[ ! -d /sys/class/net/"${INTERFACE}"/wireless ||
  "$(cat /sys/class/net/"$INTERFACE"/operstate)" = 'down' ]] && exit

SSID=$(nmcli device show wlan0 | awk '/GENERAL.CONNECTION:/ {for (i=2; i<NF; i++) printf $i " "; print $NF}')

QUALITY=$(iw dev "${INTERFACE}" link | grep 'dBm$' | grep -Eoe '-[0-9]{2}' | awk '{print  ($1 > -50 ? 100 :($1 < -100 ? 0 : ($1+100)*2))}')

echo "󰖩 $SSID $QUALITY%" # full text
echo "󰖩 $SSID"           # short text
echo "#b8bb26"           # color
